CREATE TABLE IF NOT EXISTS bronze.erp_CUST_AZ12(
    CID VARCHAR(50),
    BDATE DATE,
    GEN VARCHAR(50)
);


CREATE TABLE IF NOT EXISTS bronze.erp_LOC_A101(
    CID VARCHAR(50),
    CNTRY VARCHAR(50)
);

CREATE TABLE IF NOT EXISTS bronze.erp_PX_CAT_G1V2(
    ID VARCHAR(50),
    CAT VARCHAR(50),
    SUBCAT VARCHAR(50),
    MAINTENANCE VARCHAR(50)
);